name: Commit Photo Log

on:
  schedule:
    - cron: '0 * * * *'
  push:
    paths:
      - 'data/photo_log.csv'

jobs:
  commit-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Commit CSV log
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -B logs
          git add data/photo_log.csv
          git commit -m "Update photo log [skip ci]" || echo "No changes"
          git push origin logs --force